name: msys2

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  stock:
    name: Stock
    runs-on: windows-latest
    defaults:
      # Reduce verbosity and always run with msys2 as the default shell.
      # See https://github.com/marketplace/actions/setup-msys2 .
      run:
        shell: msys2 {0}
    steps:
      - name: Set up prerequisites
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-svt-av1

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build
        run: |
          uname
          echo $MSYSTEM
          cd src
          objdump -f -t /mingw64/lib/libSvtAv1Enc.a
          nm /mingw64/lib/libSvtAv1Enc.a | grep svt_av1_get_version
          make -f Makefile.msys2
